version: '3.8'

services:
  http-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: http-proxy-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: Add logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
